version: "3.8"

networks:
  mis-jfn_network:
    driver: bridge

services:
    user-management:
      image: user-management
      container_name: user-management
      build:
        context: ../src/services/user-management
      ports:
        - 5000:5000
      networks:
      - mis-jfn_network
      restart: on-failure

    admissions:
      image: admissions
      container_name: admissions
      build:
        context: ../src/services/admissions
      ports:
        - 5002:5002
      networks:
      - mis-jfn_network
      restart: on-failure

    faculties:
      image: faculties
      container_name: faculties
      build:
        context: ../src/services/faculties
      ports:
        - 5001:5001
      networks:
      - mis-jfn_network
      restart: on-failure

    admin-portal:
      image: admin-portal
      container_name: admin-portal
      build:
        context: ../src/apps/admin-portal
      env_file: ../src/apps/admin-portal/docker.env
      depends_on:
        - user-management
        - admissions
        - faculites
      networks:
      - mis-jfn_network
      restart: on-failure


    student-portal:
      image: student-portal
      container_name: student-portal
      build:
        context: ../src/apps/student-portal
      env_file: ../src/apps/student-portal/docker.env
      depends_on:
        - user-management
        - admissions
        - faculites
      networks:
      - mis-jfn_network
      restart: on-failure

    
    token-validation:
      image: token-validation
      container_name: token-validation
      build:
        context: ../src/services/token-validation
      ports:
        - 5003:5003
      networks:
      - mis-jfn_network
      restart: on-failure   


    reverse-proxy:
      image: nginx:latest
      container_name: reverse-proxy
      depends_on:
        - user-management
        - admissions
        - faculites
        - admin-portal
      volumes:
        - ../.nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
      - mis-jfn_network
      ports:
        - 80:80
        - 81:81
        - 82:82