version: "3.8"
services:
    user-management:
      image: user-management
      container_name: user-management
      build:
        context: ../src/services/user-management
      ports:
        - 5000:5000
      restart: on-failure

    admissions:
      image: admissions
      container_name: admissions
      build:
        context: ../src/services/admissions
      ports:
        - 5002:5002
      restart: on-failure

    faculties:
      image: faculties
      container_name: faculties
      build:
        context: ../src/services/faculties
      ports:
        - 5001:5001
      restart: on-failure

    admin-portal:
      image: admin-portal
      container_name: admin-portal
      build:
        context: ../src/apps/admin-portal
      depends_on:
        - user-management
        - admissions
        - faculites
      ports:
        - 8081:80
      restart: on-failure


    student-portal:
      image: student-portal
      container_name: student-portal
      build:
        context: ../src/apps/student-portal
      depends_on:
        - user-management
        - admissions
        - faculites
      ports:
        - 8080:80
      restart: on-failure


    reverse-proxy:
      image: nginx:1.17.10
      container_name: reverse-proxy
      depends_on:
        - user-management
        - admissions
        - faculites
        - admin-portal
      volumes:
        - ../.nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80