version: '3'

services:
    docker-registry:
        container_name: docker-registry
        image: registry:2
        ports:
            - 5000:5000
        restart: always
        volumes:
            - ./volume:/var/lib/registry
    
    docker-registry-ui:
        container_name: docker-registry-ui
        image: konradkleine/docker-registry-frontend:v2
        ports:
            - 8080:80
        restart: always
        environment:
            ENV_DOCKER_REGISTRY_HOST: docker-registry
            ENV_DOCKER_REGISTRY_PORT: 5000

    jenkins:
        container_name: jenkins
        image: jenkinsci/blueocean
        privileged: true
        user: root
        ports:
            - 9080:8080
            - 50000:50000
        volumes:
            - jenkins_data:/var/jenkins_home
volumes:
    jenkins_data:
        driver: local


# f3227a6348f34e32b245a473eb9abe75